name: Publish module to Powershell Gallery

on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: print list items
        run: ls -l /github/workspace

    # Publishing the module to powershell gallery        
      - name: Publish to Powershell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }} # Using the NugetAPI key set in GitHub Secrets
