name: Publish module to Powershell Gallery

on:
  workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    # Publishing the module to powershell gallery        
#       - name: Publish to Powershell Gallery
#         uses: pcgeek86/publish-powershell-module-action@v20
#         id: publish-module
#         with:
#           NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }} # Using the NugetAPI key set in GitHub Secrets
#           modulePath: /home/runner/work/OpenProviderPowershell/
#   publish:
#     needs: checkout
#     runs-on: ubuntu-latest
#     steps:
#       - name: Publish to Powershell Gallery
#         uses: pcgeek86/publish-powershell-module-action@v20
#         id: publish-module
#         with:
#           NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }} # Using the NugetAPI key set in GitHub Secrets

  publishv2:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Publish PowerShell Module
        uses: natescherer/update-powershell-metadata-action@v1
        with:
          token: ${{ secrets.PS_GALLERY_KEY }}
          target: gallery
          path: src
